/**
 * This file was auto-generated by openapi-typescript.
 * Do not make direct changes to the file.
 */

export interface paths {
    "/api/v1/auth/login": {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        get?: never;
        put?: never;
        /** Sign in */
        post: operations["login_api_v1_auth_login_post"];
        delete?: never;
        options?: never;
        head?: never;
        patch?: never;
        trace?: never;
    };
    "/api/v1/auth/logout": {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        get?: never;
        put?: never;
        /** Sign out */
        post: operations["logout_api_v1_auth_logout_post"];
        delete?: never;
        options?: never;
        head?: never;
        patch?: never;
        trace?: never;
    };
    "/api/v1/auth/password": {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        get?: never;
        put?: never;
        /** Change my password */
        post: operations["change_password_api_v1_auth_password_post"];
        delete?: never;
        options?: never;
        head?: never;
        patch?: never;
        trace?: never;
    };
    "/api/v1/auth/session": {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        /** Current session */
        get: operations["current_session_api_v1_auth_session_get"];
        put?: never;
        post?: never;
        delete?: never;
        options?: never;
        head?: never;
        patch?: never;
        trace?: never;
    };
    "/api/v1/health": {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        /** Liveness probe */
        get: operations["liveness_api_v1_health_get"];
        put?: never;
        post?: never;
        delete?: never;
        options?: never;
        head?: never;
        patch?: never;
        trace?: never;
    };
    "/api/v1/health/ready": {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        /** Readiness probe */
        get: operations["readiness_api_v1_health_ready_get"];
        put?: never;
        post?: never;
        delete?: never;
        options?: never;
        head?: never;
        patch?: never;
        trace?: never;
    };
    "/api/v1/oauth/{integration}/callback": {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        /** Provider redirect target (always answers with a redirect into the app) */
        get: operations["oauth_callback_api_v1_oauth__integration__callback_get"];
        put?: never;
        post?: never;
        delete?: never;
        options?: never;
        head?: never;
        patch?: never;
        trace?: never;
    };
    "/api/v1/workspaces": {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        /** Workspaces I belong to */
        get: operations["list_my_workspaces_api_v1_workspaces_get"];
        put?: never;
        post?: never;
        delete?: never;
        options?: never;
        head?: never;
        patch?: never;
        trace?: never;
    };
    "/api/v1/workspaces/{workspace_id}": {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        /** One workspace */
        get: operations["get_workspace_api_v1_workspaces__workspace_id__get"];
        put?: never;
        post?: never;
        delete?: never;
        options?: never;
        head?: never;
        patch?: never;
        trace?: never;
    };
    "/api/v1/workspaces/{workspace_id}/connections/{connection_id}": {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        /** One connection */
        get: operations["get_connection_api_v1_workspaces__workspace_id__connections__connection_id__get"];
        put?: never;
        post?: never;
        /** Disconnect: revoke access, delete credentials, remove the connection */
        delete: operations["disconnect_api_v1_workspaces__workspace_id__connections__connection_id__delete"];
        options?: never;
        head?: never;
        patch?: never;
        trace?: never;
    };
    "/api/v1/workspaces/{workspace_id}/connections/{connection_id}/account": {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        get?: never;
        put?: never;
        /** Choose the account this connection reads */
        post: operations["select_account_api_v1_workspaces__workspace_id__connections__connection_id__account_post"];
        delete?: never;
        options?: never;
        head?: never;
        patch?: never;
        trace?: never;
    };
    "/api/v1/workspaces/{workspace_id}/connections/{connection_id}/accounts": {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        /** Accounts the authorised login can see (e.g. Zoho organisations) */
        get: operations["list_accounts_api_v1_workspaces__workspace_id__connections__connection_id__accounts_get"];
        put?: never;
        post?: never;
        delete?: never;
        options?: never;
        head?: never;
        patch?: never;
        trace?: never;
    };
    "/api/v1/workspaces/{workspace_id}/connections/{connection_id}/assistant": {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        /** The assistant for this connection */
        get: operations["get_assistant_api_v1_workspaces__workspace_id__connections__connection_id__assistant_get"];
        put?: never;
        post?: never;
        delete?: never;
        options?: never;
        head?: never;
        patch?: never;
        trace?: never;
    };
    "/api/v1/workspaces/{workspace_id}/connections/{connection_id}/assistant/conversations": {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        /** Your conversations */
        get: operations["list_conversations_api_v1_workspaces__workspace_id__connections__connection_id__assistant_conversations_get"];
        put?: never;
        /** Start a conversation */
        post: operations["create_conversation_api_v1_workspaces__workspace_id__connections__connection_id__assistant_conversations_post"];
        delete?: never;
        options?: never;
        head?: never;
        patch?: never;
        trace?: never;
    };
    "/api/v1/workspaces/{workspace_id}/connections/{connection_id}/assistant/conversations/{conversation_id}": {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        /** A conversation */
        get: operations["get_conversation_api_v1_workspaces__workspace_id__connections__connection_id__assistant_conversations__conversation_id__get"];
        put?: never;
        post?: never;
        /** Delete a conversation */
        delete: operations["delete_conversation_api_v1_workspaces__workspace_id__connections__connection_id__assistant_conversations__conversation_id__delete"];
        options?: never;
        head?: never;
        patch?: never;
        trace?: never;
    };
    "/api/v1/workspaces/{workspace_id}/connections/{connection_id}/assistant/conversations/{conversation_id}/messages": {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        get?: never;
        put?: never;
        /** Ask the assistant */
        post: operations["send_message_api_v1_workspaces__workspace_id__connections__connection_id__assistant_conversations__conversation_id__messages_post"];
        delete?: never;
        options?: never;
        head?: never;
        patch?: never;
        trace?: never;
    };
    "/api/v1/workspaces/{workspace_id}/connections/{connection_id}/finance/balance-sheet": {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        /** Balance Sheet tab (pending the director's definition) */
        get: operations["get_balance_sheet_api_v1_workspaces__workspace_id__connections__connection_id__finance_balance_sheet_get"];
        put?: never;
        post?: never;
        delete?: never;
        options?: never;
        head?: never;
        patch?: never;
        trace?: never;
    };
    "/api/v1/workspaces/{workspace_id}/connections/{connection_id}/finance/gst": {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        /** GST tab (pending the director's definition) */
        get: operations["get_gst_api_v1_workspaces__workspace_id__connections__connection_id__finance_gst_get"];
        put?: never;
        post?: never;
        delete?: never;
        options?: never;
        head?: never;
        patch?: never;
        trace?: never;
    };
    "/api/v1/workspaces/{workspace_id}/connections/{connection_id}/finance/invoices": {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        /** Invoice register, newest first */
        get: operations["get_invoices_api_v1_workspaces__workspace_id__connections__connection_id__finance_invoices_get"];
        put?: never;
        post?: never;
        delete?: never;
        options?: never;
        head?: never;
        patch?: never;
        trace?: never;
    };
    "/api/v1/workspaces/{workspace_id}/connections/{connection_id}/finance/overview": {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        /** Overview tab */
        get: operations["get_overview_api_v1_workspaces__workspace_id__connections__connection_id__finance_overview_get"];
        put?: never;
        post?: never;
        delete?: never;
        options?: never;
        head?: never;
        patch?: never;
        trace?: never;
    };
    "/api/v1/workspaces/{workspace_id}/connections/{connection_id}/finance/receivables": {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        /** Receivables tab */
        get: operations["get_receivables_api_v1_workspaces__workspace_id__connections__connection_id__finance_receivables_get"];
        put?: never;
        post?: never;
        delete?: never;
        options?: never;
        head?: never;
        patch?: never;
        trace?: never;
    };
    "/api/v1/workspaces/{workspace_id}/connections/{connection_id}/finance/trends": {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        /** Trends & Analysis tab */
        get: operations["get_trends_api_v1_workspaces__workspace_id__connections__connection_id__finance_trends_get"];
        put?: never;
        post?: never;
        delete?: never;
        options?: never;
        head?: never;
        patch?: never;
        trace?: never;
    };
    "/api/v1/workspaces/{workspace_id}/connections/{connection_id}/sync": {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        /** How current this connection's data is */
        get: operations["get_sync_api_v1_workspaces__workspace_id__connections__connection_id__sync_get"];
        put?: never;
        /** Refresh this connection's data (runs in the background) */
        post: operations["request_sync_api_v1_workspaces__workspace_id__connections__connection_id__sync_post"];
        delete?: never;
        options?: never;
        head?: never;
        patch?: never;
        trace?: never;
    };
    "/api/v1/workspaces/{workspace_id}/integrations": {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        /** Integrations for this workspace */
        get: operations["list_integrations_api_v1_workspaces__workspace_id__integrations_get"];
        put?: never;
        post?: never;
        delete?: never;
        options?: never;
        head?: never;
        patch?: never;
        trace?: never;
    };
    "/api/v1/workspaces/{workspace_id}/integrations/{integration}": {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        /** One integration */
        get: operations["get_integration_api_v1_workspaces__workspace_id__integrations__integration__get"];
        put?: never;
        post?: never;
        delete?: never;
        options?: never;
        head?: never;
        patch?: never;
        trace?: never;
    };
    "/api/v1/workspaces/{workspace_id}/integrations/{integration}/connect": {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        get?: never;
        put?: never;
        /** Start connecting (or reconnecting) an integration */
        post: operations["connect_api_v1_workspaces__workspace_id__integrations__integration__connect_post"];
        delete?: never;
        options?: never;
        head?: never;
        patch?: never;
        trace?: never;
    };
    "/api/v1/workspaces/{workspace_id}/members": {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        /** Workspace members */
        get: operations["list_members_api_v1_workspaces__workspace_id__members_get"];
        put?: never;
        post?: never;
        delete?: never;
        options?: never;
        head?: never;
        patch?: never;
        trace?: never;
    };
}
export type webhooks = Record<string, never>;
export interface components {
    schemas: {
        /** ActionItemOut */
        ActionItemOut: {
            /** Amount */
            amount: string;
            /** Days Overdue */
            days_overdue: number | null;
            /** Detail */
            detail: string;
            /** Due Date */
            due_date: string | null;
            /**
             * Kind
             * @enum {string}
             */
            kind: "overdue_invoice" | "gst_payable" | "accrual_loss";
            /** Reference */
            reference: string | null;
            /**
             * Severity
             * @enum {string}
             */
            severity: "high" | "medium" | "low";
            /** Title */
            title: string;
        };
        /** AgeBucketOut */
        AgeBucketOut: {
            /** Amount */
            amount: string;
            /** Count */
            count: number;
            /** Key */
            key: string;
            /** Label */
            label: string;
        };
        /** AssistantInfo */
        AssistantInfo: {
            /**
             * Available
             * @description False when no AI provider is configured on the server
             */
            available: boolean;
            /** Display Name */
            display_name: string;
            /** Domain */
            domain: string;
            status: components["schemas"]["AssistantStatus"];
            /** Suggested Questions */
            suggested_questions: string[];
        };
        /**
         * AssistantStatus
         * @description What the AI provider's own responses last reported (never guessed). `unconfirmed`: nothing
         *     known yet, or a limit's reset time has passed; the next question's real response decides.
         */
        AssistantStatus: {
            /** Limit Scope */
            limit_scope?: ("daily" | "minute") | null;
            /**
             * Resets In Seconds
             * @description Seconds until questions are accepted again, from the provider's reply
             */
            resets_in_seconds?: number | null;
            /**
             * State
             * @enum {string}
             */
            state: "available" | "limit_reached" | "unconfirmed" | "not_configured";
        };
        /** BalanceGroup */
        BalanceGroup: {
            /** Lines */
            lines: components["schemas"]["BalanceLineOut"][];
            /** Name */
            name: string;
            /** Total */
            total: string;
        };
        /** BalanceLineOut */
        BalanceLineOut: {
            /** Balance */
            balance: string;
            /** Name */
            name: string;
        };
        /** BalanceSheet */
        BalanceSheet: {
            /** As Of */
            as_of: string | null;
            /**
             * Basis
             * @default balance
             * @enum {string}
             */
            basis: "accrual" | "cash" | "billed" | "balance" | "ledger";
            /** Cash On Hand */
            cash_on_hand: string;
            /** Groups */
            groups: components["schemas"]["BalanceGroup"][];
            meta: components["schemas"]["Meta"];
            /**
             * Pending Definition
             * @description Awaiting the director's definition (Q6)
             * @default true
             */
            pending_definition: boolean;
        };
        /** CashBucketOut */
        CashBucketOut: {
            /** Cash In */
            cash_in: string;
            /** Cash Out */
            cash_out: string;
            /** Net */
            net: string;
            /**
             * Start
             * Format: date
             */
            start: string;
        };
        /** CategoryMonth */
        CategoryMonth: {
            /** Amounts */
            amounts: {
                [key: string]: string;
            };
            /**
             * Month
             * Format: date
             */
            month: string;
            /**
             * Other
             * @description Categories outside the top five
             */
            other: string;
        };
        /** Change */
        Change: {
            /** Compared To */
            compared_to: string;
            /**
             * Percent
             * @description (current − previous) ÷ |previous| × 100
             */
            percent: string | null;
        };
        /** ChangePasswordRequest */
        ChangePasswordRequest: {
            /** Current Password */
            current_password: string;
            /** New Password */
            new_password: string;
        };
        /** ClientBilled */
        ClientBilled: {
            /** Billed */
            billed: string;
            /** Has Overdue */
            has_overdue: boolean;
            /** Outstanding */
            outstanding: string;
            /** Overdue */
            overdue: string;
            /** Party Name */
            party_name: string;
        };
        /** ConnectRequest */
        ConnectRequest: {
            /**
             * Region
             * @description Provider data center; the default if omitted
             */
            region?: string | null;
        };
        /** ConnectResponse */
        ConnectResponse: {
            /**
             * Redirect Url
             * @description Send the browser here to continue (e.g. provider consent)
             */
            redirect_url: string;
        };
        /**
         * ConnectionAccount
         * @description The external account the connection reads (e.g. a Zoho Books organisation).
         */
        ConnectionAccount: {
            /** Currency */
            currency?: string | null;
            /** Fiscal Year Start Month */
            fiscal_year_start_month?: number | null;
            /** Id */
            id: string;
            /** Name */
            name: string;
            /** Timezone */
            timezone?: string | null;
        };
        /** ConnectionOut */
        ConnectionOut: {
            account: components["schemas"]["ConnectionAccount"] | null;
            /**
             * Authorised
             * @description Credentials are stored (consent was given)
             */
            authorised: boolean;
            /** Connected At */
            connected_at: string | null;
            /**
             * Connected By
             * @description Name of the person who connected it
             */
            connected_by: string | null;
            /**
             * Id
             * Format: uuid
             */
            id: string;
            /** Integration Key */
            integration_key: string;
            /** Last Error Code */
            last_error_code: string | null;
            /** Last Verified At */
            last_verified_at: string | null;
            /** Region */
            region: string | null;
            /**
             * Status
             * @enum {string}
             */
            status: "pending" | "connected" | "needs_reauth" | "error";
        };
        /** ConversationDetail */
        ConversationDetail: {
            /**
             * Created At
             * Format: date-time
             */
            created_at: string;
            /**
             * Id
             * Format: uuid
             */
            id: string;
            /** Last Message At */
            last_message_at: string | null;
            /** Messages */
            messages: components["schemas"]["MessageOut"][];
            /** Title */
            title: string | null;
        };
        /** ConversationList */
        ConversationList: {
            /** Conversations */
            conversations: components["schemas"]["ConversationSummary"][];
        };
        /** ConversationSummary */
        ConversationSummary: {
            /**
             * Created At
             * Format: date-time
             */
            created_at: string;
            /**
             * Id
             * Format: uuid
             */
            id: string;
            /** Last Message At */
            last_message_at: string | null;
            /** Title */
            title: string | null;
        };
        /** DatasetStatusOut */
        DatasetStatusOut: {
            /** Error Code */
            error_code: string | null;
            /** Key */
            key: string;
            /** Label */
            label: string;
            /** Last Attempt At */
            last_attempt_at: string | null;
            /** Last Success At */
            last_success_at: string | null;
            /** Row Count */
            row_count: number | null;
            /**
             * Status
             * @enum {string}
             */
            status: "ok" | "failed" | "never";
            /** Window End */
            window_end: string | null;
            /** Window Start */
            window_start: string | null;
        };
        /** ExpenseShare */
        ExpenseShare: {
            /** Amount */
            amount: string;
            /** Name */
            name: string;
            /**
             * Share
             * @description Percent of the total
             */
            share: string | null;
        };
        /** ExternalAccountList */
        ExternalAccountList: {
            /** Accounts */
            accounts: components["schemas"]["ExternalAccountOut"][];
        };
        /** ExternalAccountOut */
        ExternalAccountOut: {
            /** Detail */
            detail: string;
            /** Id */
            id: string;
            /** Is Default */
            is_default: boolean;
            /** Name */
            name: string;
            /** Selectable */
            selectable: boolean;
        };
        /** Freshness */
        Freshness: {
            /**
             * As Of
             * @description Oldest successful dataset refresh
             */
            as_of: string | null;
            /**
             * Data Version
             * @description Id of the last sync that wrote data
             */
            data_version: string | null;
            /**
             * Sync State
             * @enum {string}
             */
            sync_state: "idle" | "running";
        };
        /** GstOut */
        GstOut: {
            /** As Of */
            as_of: string | null;
            /**
             * Basis
             * @default ledger
             * @enum {string}
             */
            basis: "accrual" | "cash" | "billed" | "balance" | "ledger";
            /** Input Tax */
            input_tax: string | null;
            meta: components["schemas"]["Meta"];
            /** Net Payable */
            net_payable: string | null;
            /** Output Tax */
            output_tax: string | null;
            /**
             * Pending Definition
             * @description Awaiting the director's definition (Q5)
             * @default true
             */
            pending_definition: boolean;
        };
        /** HTTPValidationError */
        HTTPValidationError: {
            /** Detail */
            detail?: components["schemas"]["ValidationError"][];
        };
        /** IntegrationList */
        IntegrationList: {
            /** Integrations */
            integrations: components["schemas"]["IntegrationTile"][];
        };
        /** IntegrationTile */
        IntegrationTile: {
            /**
             * Account Noun
             * @description What one external account is called ("organisation")
             */
            account_noun: string;
            /**
             * Availability
             * @enum {string}
             */
            availability: "available" | "coming_soon";
            /**
             * Can Manage
             * @description Whether the caller may connect/disconnect it
             */
            can_manage: boolean;
            /** @description The live connection, if any */
            connection: components["schemas"]["ConnectionOut"] | null;
            /**
             * Connection State
             * @enum {string}
             */
            connection_state: "not_connected" | "pending" | "connected" | "needs_reauth" | "error" | "coming_soon";
            /** Domain */
            domain: string;
            /** Domain Name */
            domain_name: string;
            /** Key */
            key: string;
            /** Name */
            name: string;
            /** Read Only */
            read_only: boolean;
            /**
             * Reads
             * @description Plain-language list of the data Clario reads
             */
            reads: string[];
            /**
             * Regions
             * @description Data centers to choose from; first is default
             */
            regions: components["schemas"]["RegionOut"][];
            /** Summary */
            summary: string;
            /** Vendor */
            vendor: string;
        };
        /** InvoiceOut */
        InvoiceOut: {
            /** Balance */
            balance: string;
            /** Currency */
            currency: string;
            /** Days Overdue */
            days_overdue: number;
            /** Due Date */
            due_date: string | null;
            /**
             * Id
             * Format: uuid
             */
            id: string;
            /**
             * Invoice Date
             * Format: date
             */
            invoice_date: string;
            /** Invoice Number */
            invoice_number: string;
            /** Party Name */
            party_name: string;
            /**
             * Status
             * @enum {string}
             */
            status: "draft" | "void" | "paid" | "partially_paid" | "open" | "overdue" | "unknown";
            /** Total */
            total: string;
            /**
             * Total Document
             * @description In the invoice's own currency
             */
            total_document: string;
        };
        /** InvoicePage */
        InvoicePage: {
            /** Items */
            items: components["schemas"]["InvoiceOut"][];
            /** Next Cursor */
            next_cursor: string | null;
        };
        /** Kpi */
        Kpi: {
            /**
             * Basis
             * @enum {string}
             */
            basis: "accrual" | "cash" | "billed" | "balance" | "ledger";
            change?: components["schemas"]["Change"] | null;
            /**
             * Count
             * @description e.g. overdue invoices for receivables
             */
            count?: number | null;
            /** Key */
            key: string;
            /** Label */
            label: string;
            /** Note */
            note?: string | null;
            /**
             * Ratio
             * @description Percent: collection ratio, net margin
             */
            ratio?: string | null;
            /** @description e.g. {"billed": 895675} for collected */
            related?: components["schemas"]["NamedAmount"] | null;
            /** Value */
            value: string;
            window: components["schemas"]["Window"];
        };
        /** Liveness */
        Liveness: {
            /**
             * Status
             * @default ok
             * @constant
             */
            status: "ok";
            /**
             * Version
             * @default 0.1.0
             */
            version: string;
        };
        /** LoginRequest */
        LoginRequest: {
            /** Email */
            email: string;
            /** Password */
            password: string;
        };
        /** Member */
        Member: {
            /** Email */
            email: string;
            /** Full Name */
            full_name: string;
            role: components["schemas"]["Role"];
            /**
             * User Id
             * Format: uuid
             */
            user_id: string;
        };
        /** MemberList */
        MemberList: {
            /** Members */
            members: components["schemas"]["Member"][];
        };
        /** MessageOut */
        MessageOut: {
            /**
             * As Of
             * @description Data freshness of the figures used
             */
            as_of?: string | null;
            /** Content */
            content: string;
            /**
             * Created At
             * Format: date-time
             */
            created_at: string;
            /**
             * Id
             * Format: uuid
             */
            id: string;
            /**
             * Role
             * @enum {string}
             */
            role: "user" | "assistant";
            /**
             * Sources
             * @description For "Based on …" (assistant)
             */
            sources?: string[];
            /**
             * Status
             * @enum {string}
             */
            status: "complete" | "failed";
        };
        /** Meta */
        Meta: {
            /** Currency */
            currency: string;
            /**
             * Fiscal Year
             * @description e.g. "FY 2026-27"
             */
            fiscal_year: string;
            /** Fiscal Year Start Month */
            fiscal_year_start_month: number;
            freshness: components["schemas"]["Freshness"];
            /** Organisation */
            organisation: string;
            /**
             * Today
             * Format: date
             * @description Today in the organisation's time zone
             */
            today: string;
        };
        /** MonthFigures */
        MonthFigures: {
            /** Billed */
            billed: string;
            /** Collected */
            collected: string;
            /** Expenses */
            expenses: string;
            /**
             * Month
             * Format: date
             */
            month: string;
            /** Net Cash */
            net_cash: string;
        };
        /** NamedAmount */
        NamedAmount: {
            /** Amount */
            amount: string;
            /** Name */
            name: string;
        };
        /** Overview */
        Overview: {
            /** Actions */
            actions: components["schemas"]["ActionItemOut"][];
            /**
             * Expense Mix
             * @description Operating expenses by account (accrual)
             */
            expense_mix: components["schemas"]["ExpenseShare"][];
            expense_mix_window: components["schemas"]["Window"];
            /** Kpis */
            kpis: components["schemas"]["Kpi"][];
            meta: components["schemas"]["Meta"];
            /**
             * Months
             * @description Billed vs collected vs expenses (cash)
             */
            months: components["schemas"]["MonthFigures"][];
            pnl: components["schemas"]["PnlStatement"];
            register_totals: components["schemas"]["RegisterTotalsOut"];
            /** Revenue By Client */
            revenue_by_client: components["schemas"]["ClientBilled"][];
        };
        /**
         * Permission
         * @enum {string}
         */
        Permission: "workspace.view" | "finance.view" | "assistant.use" | "integrations.manage" | "members.manage";
        /** PnlStatement */
        PnlStatement: {
            /**
             * Basis
             * @default accrual
             * @enum {string}
             */
            basis: "accrual" | "cash" | "billed" | "balance" | "ledger";
            /** Cogs */
            cogs: string;
            /** Gross Margin */
            gross_margin: string | null;
            /** Gross Profit */
            gross_profit: string;
            largest_cost: components["schemas"]["NamedAmount"] | null;
            /**
             * Latest Month Spend
             * @description Cash expenses of the current month (the PDF's run-rate note; director Q3)
             */
            latest_month_spend: string;
            /** Net Margin */
            net_margin: string | null;
            /** Net Pnl */
            net_pnl: string;
            /** Operating Expenses */
            operating_expenses: string;
            /**
             * Other Expenses
             * @description Non-operating; not in net P&L (director Q4)
             */
            other_expenses: string;
            /**
             * Other Income
             * @description Non-operating; not in net P&L (director Q4)
             */
            other_income: string;
            /** Revenue */
            revenue: string;
            /** Total Costs */
            total_costs: string;
            window: components["schemas"]["Window"];
        };
        /** Readiness */
        Readiness: {
            /** Checks */
            checks: {
                [key: string]: "ok";
            };
            /**
             * Status
             * @default ready
             * @constant
             */
            status: "ready";
        };
        /** Receivables */
        Receivables: {
            /** Ageing */
            ageing: components["schemas"]["AgeBucketOut"][];
            /**
             * Basis
             * @default balance
             * @enum {string}
             */
            basis: "accrual" | "cash" | "billed" | "balance" | "ledger";
            /** By Client */
            by_client: components["schemas"]["ClientBilled"][];
            /**
             * Invoices
             * @description Every receivable, most overdue first
             */
            invoices: components["schemas"]["InvoiceOut"][];
            meta: components["schemas"]["Meta"];
            /** Open Count */
            open_count: number;
            /** Outstanding */
            outstanding: string;
            /** Overdue */
            overdue: string;
            /** Overdue Count */
            overdue_count: number;
        };
        /** RegionOut */
        RegionOut: {
            /** Code */
            code: string;
            /** Label */
            label: string;
        };
        /** RegisterTotalsOut */
        RegisterTotalsOut: {
            /** Balance */
            balance: string;
            /** Billed */
            billed: string;
            /** Count */
            count: number;
        };
        /** Reply */
        Reply: {
            assistant_message: components["schemas"]["MessageOut"];
            conversation: components["schemas"]["ConversationSummary"];
            user_message: components["schemas"]["MessageOut"];
        };
        /**
         * Role
         * @enum {string}
         */
        Role: "owner" | "admin" | "member" | "viewer";
        /** SelectAccountRequest */
        SelectAccountRequest: {
            /** Account Id */
            account_id: string;
        };
        /** SendMessage */
        SendMessage: {
            /** Content */
            content: string;
        };
        /**
         * SessionOut
         * @description What the SPA needs after sign-in or on reload.
         */
        SessionOut: {
            /**
             * Csrf Token
             * @description Send as the X-CSRF-Token header on every non-GET request
             */
            csrf_token: string;
            /** Expires At */
            expires_at?: string | null;
            user: components["schemas"]["UserOut"];
            /** Workspaces */
            workspaces: components["schemas"]["WorkspaceSummary"][];
        };
        /** SyncRequest */
        SyncRequest: {
            /**
             * Mode
             * @description manual: 'Refresh now' (cooldown applies); if_stale: only when data is stale
             * @default manual
             * @enum {string}
             */
            mode: "manual" | "if_stale";
        };
        /** SyncRunOut */
        SyncRunOut: {
            /** Api Calls */
            api_calls: number;
            /** Error Code */
            error_code: string | null;
            /** Finished At */
            finished_at: string | null;
            /**
             * Id
             * Format: uuid
             */
            id: string;
            /**
             * Started At
             * Format: date-time
             */
            started_at: string;
            /**
             * Status
             * @enum {string}
             */
            status: "running" | "succeeded" | "partial" | "failed";
            /**
             * Trigger
             * @enum {string}
             */
            trigger: "initial" | "manual" | "stale" | "scheduled";
        };
        /** SyncStatus */
        SyncStatus: {
            /**
             * As Of
             * @description Oldest successful refresh among the datasets; null until all have data
             */
            as_of: string | null;
            /** Datasets */
            datasets: components["schemas"]["DatasetStatusOut"][];
            /** @description The run in progress, else the latest one */
            run: components["schemas"]["SyncRunOut"] | null;
            /**
             * State
             * @enum {string}
             */
            state: "idle" | "running";
        };
        /** Trends */
        Trends: {
            /**
             * Daily
             * @description Last 30 days
             */
            daily: components["schemas"]["CashBucketOut"][];
            /** Expense Trend */
            expense_trend: components["schemas"]["CategoryMonth"][];
            meta: components["schemas"]["Meta"];
            /** Months */
            months: components["schemas"]["MonthFigures"][];
            /** Top Categories */
            top_categories: string[];
            totals: components["schemas"]["MonthFigures"];
            /**
             * Weekly
             * @description Last 10 weeks, weeks start on Monday
             */
            weekly: components["schemas"]["CashBucketOut"][];
            window: components["schemas"]["Window"];
        };
        /** UserOut */
        UserOut: {
            /** Email */
            email: string;
            /** Full Name */
            full_name: string;
            /**
             * Id
             * Format: uuid
             */
            id: string;
            /** Is Platform Admin */
            is_platform_admin: boolean;
        };
        /** ValidationError */
        ValidationError: {
            /** Context */
            ctx?: Record<string, never>;
            /** Input */
            input?: unknown;
            /** Location */
            loc: (string | number)[];
            /** Message */
            msg: string;
            /** Error Type */
            type: string;
        };
        /** Window */
        Window: {
            /**
             * End
             * Format: date
             */
            end: string;
            /**
             * Label
             * @description e.g. "FY 2026-27 to date", "Apr 2025 – 25 Sep 2026"
             */
            label: string;
            /**
             * Start
             * Format: date
             */
            start: string;
        };
        /** WorkspaceDetail */
        WorkspaceDetail: {
            /** Base Currency */
            base_currency: string;
            /** Fiscal Year Start Month */
            fiscal_year_start_month: number;
            /**
             * Id
             * Format: uuid
             */
            id: string;
            /** Name */
            name: string;
            /** Permissions */
            permissions: components["schemas"]["Permission"][];
            role: components["schemas"]["Role"];
            /** Slug */
            slug: string;
            /** Status */
            status: string;
            /** Timezone */
            timezone: string;
        };
        /** WorkspaceList */
        WorkspaceList: {
            /** Workspaces */
            workspaces: components["schemas"]["WorkspaceSummary"][];
        };
        /** WorkspaceSummary */
        WorkspaceSummary: {
            /**
             * Id
             * Format: uuid
             */
            id: string;
            /** Name */
            name: string;
            role: components["schemas"]["Role"];
            /** Slug */
            slug: string;
            /** Status */
            status: string;
        };
    };
    responses: never;
    parameters: never;
    requestBodies: never;
    headers: never;
    pathItems: never;
}
export type $defs = Record<string, never>;
export interface operations {
    login_api_v1_auth_login_post: {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        requestBody: {
            content: {
                "application/json": components["schemas"]["LoginRequest"];
            };
        };
        responses: {
            /** @description Successful Response */
            200: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["SessionOut"];
                };
            };
            /** @description Incorrect email or password */
            401: {
                headers: {
                    [name: string]: unknown;
                };
                content?: never;
            };
            /** @description Validation Error */
            422: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["HTTPValidationError"];
                };
            };
            /** @description Too many attempts */
            429: {
                headers: {
                    [name: string]: unknown;
                };
                content?: never;
            };
        };
    };
    logout_api_v1_auth_logout_post: {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        requestBody?: never;
        responses: {
            /** @description Successful Response */
            204: {
                headers: {
                    [name: string]: unknown;
                };
                content?: never;
            };
        };
    };
    change_password_api_v1_auth_password_post: {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        requestBody: {
            content: {
                "application/json": components["schemas"]["ChangePasswordRequest"];
            };
        };
        responses: {
            /** @description Successful Response */
            204: {
                headers: {
                    [name: string]: unknown;
                };
                content?: never;
            };
            /** @description Validation Error */
            422: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["HTTPValidationError"];
                };
            };
        };
    };
    current_session_api_v1_auth_session_get: {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        requestBody?: never;
        responses: {
            /** @description Successful Response */
            200: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["SessionOut"];
                };
            };
        };
    };
    liveness_api_v1_health_get: {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        requestBody?: never;
        responses: {
            /** @description Successful Response */
            200: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["Liveness"];
                };
            };
        };
    };
    readiness_api_v1_health_ready_get: {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        requestBody?: never;
        responses: {
            /** @description Successful Response */
            200: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["Readiness"];
                };
            };
            /** @description A dependency is unavailable */
            503: {
                headers: {
                    [name: string]: unknown;
                };
                content?: never;
            };
        };
    };
    oauth_callback_api_v1_oauth__integration__callback_get: {
        parameters: {
            query?: never;
            header?: never;
            path: {
                integration: string;
            };
            cookie?: never;
        };
        requestBody?: never;
        responses: {
            /** @description Successful Response */
            302: {
                headers: {
                    [name: string]: unknown;
                };
                content?: never;
            };
            /** @description Validation Error */
            422: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["HTTPValidationError"];
                };
            };
        };
    };
    list_my_workspaces_api_v1_workspaces_get: {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        requestBody?: never;
        responses: {
            /** @description Successful Response */
            200: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["WorkspaceList"];
                };
            };
        };
    };
    get_workspace_api_v1_workspaces__workspace_id__get: {
        parameters: {
            query?: never;
            header?: never;
            path: {
                /** @description Workspace id */
                workspace_id: string;
            };
            cookie?: never;
        };
        requestBody?: never;
        responses: {
            /** @description Successful Response */
            200: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["WorkspaceDetail"];
                };
            };
            /** @description Validation Error */
            422: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["HTTPValidationError"];
                };
            };
        };
    };
    get_connection_api_v1_workspaces__workspace_id__connections__connection_id__get: {
        parameters: {
            query?: never;
            header?: never;
            path: {
                /** @description Connection id */
                connection_id: string;
                /** @description Workspace id */
                workspace_id: string;
            };
            cookie?: never;
        };
        requestBody?: never;
        responses: {
            /** @description Successful Response */
            200: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["ConnectionOut"];
                };
            };
            /** @description Validation Error */
            422: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["HTTPValidationError"];
                };
            };
        };
    };
    disconnect_api_v1_workspaces__workspace_id__connections__connection_id__delete: {
        parameters: {
            query?: never;
            header?: never;
            path: {
                /** @description Connection id */
                connection_id: string;
                /** @description Workspace id */
                workspace_id: string;
            };
            cookie?: never;
        };
        requestBody?: never;
        responses: {
            /** @description Successful Response */
            204: {
                headers: {
                    [name: string]: unknown;
                };
                content?: never;
            };
            /** @description Validation Error */
            422: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["HTTPValidationError"];
                };
            };
        };
    };
    select_account_api_v1_workspaces__workspace_id__connections__connection_id__account_post: {
        parameters: {
            query?: never;
            header?: never;
            path: {
                /** @description Connection id */
                connection_id: string;
                /** @description Workspace id */
                workspace_id: string;
            };
            cookie?: never;
        };
        requestBody: {
            content: {
                "application/json": components["schemas"]["SelectAccountRequest"];
            };
        };
        responses: {
            /** @description Successful Response */
            200: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["ConnectionOut"];
                };
            };
            /** @description An account is already chosen */
            409: {
                headers: {
                    [name: string]: unknown;
                };
                content?: never;
            };
            /** @description Validation Error */
            422: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["HTTPValidationError"];
                };
            };
        };
    };
    list_accounts_api_v1_workspaces__workspace_id__connections__connection_id__accounts_get: {
        parameters: {
            query?: never;
            header?: never;
            path: {
                /** @description Connection id */
                connection_id: string;
                /** @description Workspace id */
                workspace_id: string;
            };
            cookie?: never;
        };
        requestBody?: never;
        responses: {
            /** @description Successful Response */
            200: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["ExternalAccountList"];
                };
            };
            /** @description Validation Error */
            422: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["HTTPValidationError"];
                };
            };
        };
    };
    get_assistant_api_v1_workspaces__workspace_id__connections__connection_id__assistant_get: {
        parameters: {
            query?: never;
            header?: never;
            path: {
                /** @description Connection id */
                connection_id: string;
                /** @description Workspace id */
                workspace_id: string;
            };
            cookie?: never;
        };
        requestBody?: never;
        responses: {
            /** @description Successful Response */
            200: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["AssistantInfo"];
                };
            };
            /** @description Validation Error */
            422: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["HTTPValidationError"];
                };
            };
        };
    };
    list_conversations_api_v1_workspaces__workspace_id__connections__connection_id__assistant_conversations_get: {
        parameters: {
            query?: never;
            header?: never;
            path: {
                /** @description Connection id */
                connection_id: string;
                /** @description Workspace id */
                workspace_id: string;
            };
            cookie?: never;
        };
        requestBody?: never;
        responses: {
            /** @description Successful Response */
            200: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["ConversationList"];
                };
            };
            /** @description Validation Error */
            422: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["HTTPValidationError"];
                };
            };
        };
    };
    create_conversation_api_v1_workspaces__workspace_id__connections__connection_id__assistant_conversations_post: {
        parameters: {
            query?: never;
            header?: never;
            path: {
                /** @description Connection id */
                connection_id: string;
                /** @description Workspace id */
                workspace_id: string;
            };
            cookie?: never;
        };
        requestBody?: never;
        responses: {
            /** @description Successful Response */
            201: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["ConversationSummary"];
                };
            };
            /** @description Validation Error */
            422: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["HTTPValidationError"];
                };
            };
        };
    };
    get_conversation_api_v1_workspaces__workspace_id__connections__connection_id__assistant_conversations__conversation_id__get: {
        parameters: {
            query?: never;
            header?: never;
            path: {
                /** @description Conversation id */
                conversation_id: string;
                /** @description Connection id */
                connection_id: string;
                /** @description Workspace id */
                workspace_id: string;
            };
            cookie?: never;
        };
        requestBody?: never;
        responses: {
            /** @description Successful Response */
            200: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["ConversationDetail"];
                };
            };
            /** @description Validation Error */
            422: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["HTTPValidationError"];
                };
            };
        };
    };
    delete_conversation_api_v1_workspaces__workspace_id__connections__connection_id__assistant_conversations__conversation_id__delete: {
        parameters: {
            query?: never;
            header?: never;
            path: {
                /** @description Conversation id */
                conversation_id: string;
                /** @description Connection id */
                connection_id: string;
                /** @description Workspace id */
                workspace_id: string;
            };
            cookie?: never;
        };
        requestBody?: never;
        responses: {
            /** @description Successful Response */
            204: {
                headers: {
                    [name: string]: unknown;
                };
                content?: never;
            };
            /** @description Validation Error */
            422: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["HTTPValidationError"];
                };
            };
        };
    };
    send_message_api_v1_workspaces__workspace_id__connections__connection_id__assistant_conversations__conversation_id__messages_post: {
        parameters: {
            query?: never;
            header?: never;
            path: {
                /** @description Conversation id */
                conversation_id: string;
                /** @description Connection id */
                connection_id: string;
                /** @description Workspace id */
                workspace_id: string;
            };
            cookie?: never;
        };
        requestBody: {
            content: {
                "application/json": components["schemas"]["SendMessage"];
            };
        };
        responses: {
            /** @description Successful Response */
            200: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["Reply"];
                };
            };
            /** @description Validation Error */
            422: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["HTTPValidationError"];
                };
            };
            /** @description Sending too quickly, or the AI usage limit is reached */
            429: {
                headers: {
                    [name: string]: unknown;
                };
                content?: never;
            };
            /** @description Assistant unavailable or not configured */
            503: {
                headers: {
                    [name: string]: unknown;
                };
                content?: never;
            };
        };
    };
    get_balance_sheet_api_v1_workspaces__workspace_id__connections__connection_id__finance_balance_sheet_get: {
        parameters: {
            query?: never;
            header?: never;
            path: {
                /** @description Connection id */
                connection_id: string;
                /** @description Workspace id */
                workspace_id: string;
            };
            cookie?: never;
        };
        requestBody?: never;
        responses: {
            /** @description Successful Response */
            200: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["BalanceSheet"];
                };
            };
            /** @description Validation Error */
            422: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["HTTPValidationError"];
                };
            };
        };
    };
    get_gst_api_v1_workspaces__workspace_id__connections__connection_id__finance_gst_get: {
        parameters: {
            query?: never;
            header?: never;
            path: {
                /** @description Connection id */
                connection_id: string;
                /** @description Workspace id */
                workspace_id: string;
            };
            cookie?: never;
        };
        requestBody?: never;
        responses: {
            /** @description Successful Response */
            200: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["GstOut"];
                };
            };
            /** @description Validation Error */
            422: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["HTTPValidationError"];
                };
            };
        };
    };
    get_invoices_api_v1_workspaces__workspace_id__connections__connection_id__finance_invoices_get: {
        parameters: {
            query?: {
                status?: ("overdue" | "unpaid" | "paid" | "partially_paid" | "open" | "draft" | "void") | null;
                party?: string | null;
                cursor?: string | null;
                limit?: number | null;
            };
            header?: never;
            path: {
                /** @description Connection id */
                connection_id: string;
                /** @description Workspace id */
                workspace_id: string;
            };
            cookie?: never;
        };
        requestBody?: never;
        responses: {
            /** @description Successful Response */
            200: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["InvoicePage"];
                };
            };
            /** @description Validation Error */
            422: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["HTTPValidationError"];
                };
            };
        };
    };
    get_overview_api_v1_workspaces__workspace_id__connections__connection_id__finance_overview_get: {
        parameters: {
            query?: never;
            header?: never;
            path: {
                /** @description Connection id */
                connection_id: string;
                /** @description Workspace id */
                workspace_id: string;
            };
            cookie?: never;
        };
        requestBody?: never;
        responses: {
            /** @description Successful Response */
            200: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["Overview"];
                };
            };
            /** @description Validation Error */
            422: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["HTTPValidationError"];
                };
            };
        };
    };
    get_receivables_api_v1_workspaces__workspace_id__connections__connection_id__finance_receivables_get: {
        parameters: {
            query?: never;
            header?: never;
            path: {
                /** @description Connection id */
                connection_id: string;
                /** @description Workspace id */
                workspace_id: string;
            };
            cookie?: never;
        };
        requestBody?: never;
        responses: {
            /** @description Successful Response */
            200: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["Receivables"];
                };
            };
            /** @description Validation Error */
            422: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["HTTPValidationError"];
                };
            };
        };
    };
    get_trends_api_v1_workspaces__workspace_id__connections__connection_id__finance_trends_get: {
        parameters: {
            query?: never;
            header?: never;
            path: {
                /** @description Connection id */
                connection_id: string;
                /** @description Workspace id */
                workspace_id: string;
            };
            cookie?: never;
        };
        requestBody?: never;
        responses: {
            /** @description Successful Response */
            200: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["Trends"];
                };
            };
            /** @description Validation Error */
            422: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["HTTPValidationError"];
                };
            };
        };
    };
    get_sync_api_v1_workspaces__workspace_id__connections__connection_id__sync_get: {
        parameters: {
            query?: never;
            header?: never;
            path: {
                /** @description Connection id */
                connection_id: string;
                /** @description Workspace id */
                workspace_id: string;
            };
            cookie?: never;
        };
        requestBody?: never;
        responses: {
            /** @description Successful Response */
            200: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["SyncStatus"];
                };
            };
            /** @description Validation Error */
            422: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["HTTPValidationError"];
                };
            };
        };
    };
    request_sync_api_v1_workspaces__workspace_id__connections__connection_id__sync_post: {
        parameters: {
            query?: never;
            header?: never;
            path: {
                /** @description Connection id */
                connection_id: string;
                /** @description Workspace id */
                workspace_id: string;
            };
            cookie?: never;
        };
        requestBody?: {
            content: {
                "application/json": components["schemas"]["SyncRequest"] | null;
            };
        };
        responses: {
            /** @description Successful Response */
            202: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["SyncStatus"];
                };
            };
            /** @description Not connected, or needs reconnecting */
            409: {
                headers: {
                    [name: string]: unknown;
                };
                content?: never;
            };
            /** @description Validation Error */
            422: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["HTTPValidationError"];
                };
            };
            /** @description Cooldown, or the provider's daily budget is nearly used up */
            429: {
                headers: {
                    [name: string]: unknown;
                };
                content?: never;
            };
        };
    };
    list_integrations_api_v1_workspaces__workspace_id__integrations_get: {
        parameters: {
            query?: never;
            header?: never;
            path: {
                /** @description Workspace id */
                workspace_id: string;
            };
            cookie?: never;
        };
        requestBody?: never;
        responses: {
            /** @description Successful Response */
            200: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["IntegrationList"];
                };
            };
            /** @description Validation Error */
            422: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["HTTPValidationError"];
                };
            };
        };
    };
    get_integration_api_v1_workspaces__workspace_id__integrations__integration__get: {
        parameters: {
            query?: never;
            header?: never;
            path: {
                /** @description Integration key, e.g. zoho-books */
                integration: string;
                /** @description Workspace id */
                workspace_id: string;
            };
            cookie?: never;
        };
        requestBody?: never;
        responses: {
            /** @description Successful Response */
            200: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["IntegrationTile"];
                };
            };
            /** @description Validation Error */
            422: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["HTTPValidationError"];
                };
            };
        };
    };
    connect_api_v1_workspaces__workspace_id__integrations__integration__connect_post: {
        parameters: {
            query?: never;
            header?: never;
            path: {
                /** @description Integration key, e.g. zoho-books */
                integration: string;
                /** @description Workspace id */
                workspace_id: string;
            };
            cookie?: never;
        };
        requestBody?: {
            content: {
                "application/json": components["schemas"]["ConnectRequest"] | null;
            };
        };
        responses: {
            /** @description Successful Response */
            200: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["ConnectResponse"];
                };
            };
            /** @description Requires integrations.manage */
            403: {
                headers: {
                    [name: string]: unknown;
                };
                content?: never;
            };
            /** @description Unknown or not visible to this workspace */
            404: {
                headers: {
                    [name: string]: unknown;
                };
                content?: never;
            };
            /** @description Not available yet (coming soon) */
            409: {
                headers: {
                    [name: string]: unknown;
                };
                content?: never;
            };
            /** @description Validation Error */
            422: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["HTTPValidationError"];
                };
            };
        };
    };
    list_members_api_v1_workspaces__workspace_id__members_get: {
        parameters: {
            query?: never;
            header?: never;
            path: {
                /** @description Workspace id */
                workspace_id: string;
            };
            cookie?: never;
        };
        requestBody?: never;
        responses: {
            /** @description Successful Response */
            200: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["MemberList"];
                };
            };
            /** @description Validation Error */
            422: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["HTTPValidationError"];
                };
            };
        };
    };
}
